device = 'kappa_cal_racetrack_ring_';

select('::model');

w_ring = get('w_ring') * 1e6;
w_bus = get('w_bus') * 1e6;
r_ring = get('r_ring') * 1e6;
gap = get('gap') * 1e6;
l = get('l_straight_wg_of_sbs') * 1e6;


parameters = 'wring' + num2str(w_ring) +  '_wbus' + num2str(w_bus) + 
'_l' + num2str(l) + '_gap' + num2str(gap) + '_rring' + num2str(r_ring);

file_name = device + parameters + '.fsp';
save(file_name);

